---
name: LCFG-Build-PkgSpec
version: v0.0.34
author:
  - 'Stephen Quinney <squinney@inf.ed.ac.uk>'
abstract: Object-oriented interface to LCFG build metadata
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
build_requires:
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Data::Structure::Util: 0.12
  DateTime: 0
  Email::Address: 0
  Email::Valid: 0
  Moose: 0.98
  Pod::Usage: 0
  YAML::Syck: 0.98
  perl: v5.6.1
configure_requires:
  Module::Build: 0.35
provides:
  LCFG::Build::PkgSpec:
    file: lib/LCFG/Build/PkgSpec.pm
    version: v0.0.34
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
